# Default config

server:
  http_port: 3000
  https_port: 3030
  port: 3000

# `appData` is a hash of values that will be set on the `req.rendrApp` (middleware)
# and `this.app` (models, views, controllers). These are available in both the
# client and the server.
appData:
  someProperty: someValue

api:
  host: api.github.com
  protocol: https
  port: 80

# app name
apps:
  rootPath: apps
  home: # top page
    appName: home
    appPath: homeapp
  dash: # dashboard
    appName: dash
    appPath: dashapp
